services:
  college-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./college_API:/college_API
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: > 
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
      - redis

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"