services:
  college-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./college_API:/college_API
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: > 
      sh -c "gunicorn --bind 0.0.0.0:8000 config.wsgi"
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:1.25.3-alpine
    depends_on:
      - college-app
    ports:
      - "80:80"
    volumes:
      -

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"