# Generated by Django 4.2.9 on 2024-01-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_examresult_options_alter_examresult_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam'),
        ),
    ]
