# Generated by Django 4.2.9 on 2024-03-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_examresult_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Закончился'),
        ),
    ]
