# Generated by Django 4.2.9 on 2024-04-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='quantity_questions',
            field=models.IntegerField(default=5, verbose_name='Количество вопросов'),
            preserve_default=False,
        ),
    ]
