# Generated by Django 5.0.1 on 2024-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_podgroup_remove_group_name_group_course_group_facult_and_more'),
        ('users', '0003_remove_student_course_remove_student_facult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group',
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_groups', to='data.group'),
        ),
    ]
