# Generated by Django 5.0.1 on 2024-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_podgroup_remove_group_name_group_course_group_facult_and_more'),
        ('users', '0004_remove_teacher_group_teacher_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='teacher_groups', to='data.group'),
        ),
    ]
