# Generated by Django 5.0.1 on 2024-01-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='groups',
            new_name='group',
        ),
    ]
