# Generated by Django 5.0.1 on 2024-01-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_subject'),
        ('users', '0005_alter_teacher_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='teacher_subject', to='data.subject'),
        ),
    ]
