# Generated by Django 4.2.9 on 2024-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.IntegerField(default=45, verbose_name='Время на выполнение'),
            preserve_default=False,
        ),
    ]
