# Generated by Django 4.2.9 on 2024-01-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Результат экзамена', 'verbose_name_plural': 'Результаты экзаменов'},
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='exams.exam'),
        ),
    ]
